name: magicuniqueamplicons
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::pandaseq=2.8.1
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
